name: Bug Report
description: Report a bug or issue with the bot.
labels: bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug or issue, and how to reproduce it.
      placeholder: Tell me what you did!
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: 1. Go to '...'
  - type: textarea
    id: logs
    attributes:
      label: Logs Output
      description: Please provide any relevant logs or error messages.
      placeholder: Paste the logs here.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment (OS, Node.js version, etc.).
      placeholder: OS, Node.js version, etc.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
      placeholder: Any extra info?
